### ISSUE TITLE
Add typescript-language-server

### ISSUE THREAD

**Issue by geovie** [flathub/org.freedesktop.Sdk.Extension.node14#25]
Hey,

I'm implementing a MR for GNOME Builder to support the [typescript-language-server](https://github.com/typescript-language-server/typescript-language-server).

Currently I'm bundling the language server in the flatpak manifest of Builder (see https://gitlab.gnome.org/GNOME/gnome-builder/-/merge_requests/457/diffs?commit_id=48f45c0e6ab451d38dc15ee8fab5fa26803a47ee), but it would be really nice if this could be bundled with the node runtime.

Happy to create a PR if adding the language server to the runtime would be okay.

**Comment by gasinvein** [comment]
Node itself is updated automatically, which is important, since it frequently contains security updates. Updating typescript-language-server automatically currently isn't possible due to generated sources, which will need to be manually re-generated on each update. That is, it'll add significantly more maintenance work, especially given that there are multiple versioned node SDK extensions, and will be more.

**Comment by geovie** [comment]
Yes true maintenance would be increased.

Maybe it would be possible to re-generate the generated sources via a github action? So every time a PR is opened by flatpak-external-data-checker which changes the typescript-language-server the action is run and the generated sources are added as a commit to the PR.    
(I'm not sure if the flathubbot would re-trigger the build if a commit is added)

Again I'm happy to have a look at this

**Comment by gasinvein** [comment]
> every time a PR is opened by flatpak-external-data-checker which changes the typescript-language-server the action is run and the generated sources are added as a commit to the PR.

At some point we'll move away from hosted flatpak-external-data-checker and allow allow running custom post-update scripts from it, but until then this seem hackish and fragile.

Besides, typescript-language-server is kinda out of scope of an SDK extension concept, which are intended primarily to build apps, not to provide developer tools for IDEs. E.g. VSCode flatpak family have a special extension point `com.visualstudio.code.tool` for developer tools. Maybe GNOME Builder can add something like that, or even reuse the existing `com.visualstudio.code.tool.*` extensions?

**Comment by geovie** [comment]
👌 I already thought it would be out of scope for the sdk.

Thanks anyway

**Comment by chergert** [comment]
> typescript-language-server is kinda out of scope of an SDK extension concept

From the upstream Flatpak perspective the inclusion of language servers in SDKs was very much part of the plan. The original goal was always to allow tooling like IDEs to be able to access language servers from the SDK extension within the build environment so that everything is in the same process and mount namespace.

Rust was one of the first ones to do this, but it is far from the only one we want to end up that way. We'd want the same for dotnet, llvm (clangd), vala, etc.

Would you perhaps reconsider?

If not, I would guess another option would be to create a specific SDK extension for the language server that just copies the node SDK contents first. Otherwise, IDEs would need to duplicate scripts to pull/bundle all this in and we're less likely to get content deduplication in the content address store.

**Comment by gasinvein** [comment]
Well, I guess if we consider an SDK extension to have a wider "language support" role, bundled language server probably makes sense.
I'm not strictly against adding it per se, just don't want to uphold its maintenance myself. Sorry for being direct, but please note that we have four Node.js extensions already, which means four places to keep tsls up-to-date, and there are more to come, and we don't have a robust automation plan yet. Bundling `typescript-language-server` is not near as easy as the rust one, which is basically "throw in this binary and forget".
